#include <stdio.h>
#include <stdint.h>
#include "icosoc.h"

volatile uint8_t *ioshim_memory_bytes = (void*)0x20010000;
volatile uint16_t *ioshim_memory_words = (void*)0x20010000;
volatile uint32_t *ioshim_reg_reset = (void*)0x20011000;

// generated by "ioshim_asm < blink.ios"
uint16_t myprog[] = {
	0xc0f1, //   0: ldi r15 1
	0xc0d7, //   1: ldi r13 7
	0xc011, //   2: ldi r1 1
	0xcfef, //   3: main_loop: ldi r14 255
	0xa0e1, //   4: io0 r14 r1
	0xc634, //   5: ldi r3 100
	0xc624, //   6: outer_loop: ldi r2 100
	0xd3e8, //   7: inner_loop: sync 1000
	0x222f, //   8: sub r2 r15
	0xf007, //   9: bnz inner_loop
	0x0000, //   a: nop
	0x22bf, //   b: sub r3 r15
	0xf006, //   c: bnz outer_loop
	0x0000, //   d: nop
	0x038f, //   e: shl r0 r1 r15
	0x049d, //   f: shr r1 r13
	0xe003, //  10: b main_loop
	0x1890  //  11: or r1 r0
};

int main()
{
	setbuf(stdout, NULL);

	// make sure ioshim is in reset
	*ioshim_reg_reset = -1;

	// upload ioshim program
	for (int i = 0; i < sizeof(myprog)/sizeof(uint16_t); i++)
		ioshim_memory_words[i] = myprog[i];

	// start ioshim at address 0
	*ioshim_reg_reset = 0;

	return 0;
}

